<a href="https://colab.research.google.com/github/keerthanamjohn3-arch/git.demo/blob/main/KNN2With_lung_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Datasets/lung_cancer_examples.csv")
df

           Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0          John         Wick   35       3      5       4       1
1          John  Constantine   27      20      2       5       1
2        Camela     Anderson   30       0      5       2       0
3          Alex       Telles   28       0      8       1       0
4         Diego     Maradona   68       4      5       6       1
5     Cristiano      Ronaldo   34       0     10       0       0
6        Mihail          Tal   58      15     10       0       0
7         Kathy        Bates   22      12      5       2       0
8        Nicole       Kidman   45       2      6       0       0
9           Ray      Milland   52      18      4       5       1
10      Fredric        March   33       4      8       0       0
11          Yul      Brynner   18      10      6       3       0
12         Joan     Crawford   25       2      5       1       0
13         Jane        Wyman   28      20      2       8       1
14         Anna      Magnani   34      25      4       8       1
15   Katharine       Hepburn   39      18      8       1       0
16   Katharine       Hepburn   42      22      3       5       1
17       Barbra    Streisand   19      12      8       0       0
18      Maggie         Smith   62       5      4       3       1
19      Glenda       Jackson   73      10      7       6       1
20        Jane         Fonda   55      15      1       3       1
21  Maximilian        Schell   33       8      8       1       0
22     Gregory          Peck   22      20      6       2       0
23      Sidney       Poitier   44       5      8       1       0
24         Rex      Harrison   77       3      2       6       1
25         Lee        Marvin   21      20      5       3       0
26        Paul      Scofield   37      15      6       2       0
27         Rod       Steiger   34      12      8       0       0
28        John         Wayne   55      20      1       4       1
29        Gene       Hackman   40      20      2       7       1
30      Marlon        Brando   36      13      5       2       0
31        Jack        Lemmon   56      20      3       3       1
32        Jack     Nicholson   47      15      1       8       1
33       Peter        Finch    62      25      3       4       1
34     Richard      Dreyfuss   26      10      7       2       0
35      Dustin       Hoffman   25      20      8       2       0
36       Henry        Henry    59      20      3       4       1
37      Robert        Duvall   62      15      5       5       1
38       Ellen       Burstyn   33      25      8       2       0
39        Faye       Dunaway   37      10      5       3       0
40       Diane        Keaton   50      20      2       4       1
41        Jane         Fonda   47      12      8       0       0
42       Sally         Field   69      20      5       4       1
43       Sissy        Spacek   63      20      4       5       1
44     Jessica         Lange   39      15      7       2       0
45     Gwyneth       Paltrow   21      20      8       3       0
46       Halle         Berry   31      20      9       4       0
47      Nicole        Kidman   28      10      4       1       0
48    Charlize        Theron   53      20      6       3       1
49   Katharine       Hepburn   62      20      5       6       1
50   Katharine       Hepburn   42      12      6       2       0
51      Barbra     Streisand   44      30      1       6       1
52      Maggie         Smith   26      34      1       8       1
53      Glenda       Jackson   35      20      5       1       0
54      Ernest      Borgnine   26      13      6       1       0
55        Alec      Guinness   77      20      5       4       1
56    Charlton        Heston   75      15      3       5       1
57     Gregory          Peck   43      30      3       8       1
58      Sidney       Poitier   51      25      9       0       0

In [ ]:
#Check if is there any missing value
df.isna().sum()

Name       0
Surname    0
Age        0
Smokes     0
AreaQ      0
Alkhol     0
Result     0
dtype: int64

In [ ]:
# Check if all the values are in numeric
df.dtypes

Name       object
Surname    object
Age         int64
Smokes      int64
AreaQ       int64
Alkhol      int64
Result      int64
dtype: object

In [ ]:
# In the above we have non-numeric values as object, in the column Name and Surname
# Those values(Name,Surname) not dependent with cancer prediction we drop those Columns
df.drop(["Name","Surname"],axis = 1,inplace = True)
print(df)

    Age  Smokes  AreaQ  Alkhol  Result
0    35       3      5       4       1
1    27      20      2       5       1
2    30       0      5       2       0
3    28       0      8       1       0
4    68       4      5       6       1
5    34       0     10       0       0
6    58      15     10       0       0
7    22      12      5       2       0
8    45       2      6       0       0
9    52      18      4       5       1
10   33       4      8       0       0
11   18      10      6       3       0
12   25       2      5       1       0
13   28      20      2       8       1
14   34      25      4       8       1
15   39      18      8       1       0
16   42      22      3       5       1
17   19      12      8       0       0
18   62       5      4       3       1
19   73      10      7       6       1
20   55      15      1       3       1
21   33       8      8       1       0
22   22      20      6       2       0
23   44       5      8       1       0
24   77       3      2       6       1
25   21      20      5       3       0
26   37      15      6       2       0
27   34      12      8       0       0
28   55      20      1       4       1
29   40      20      2       7       1
30   36      13      5       2       0
31   56      20      3       3       1
32   47      15      1       8       1
33   62      25      3       4       1
34   26      10      7       2       0
35   25      20      8       2       0
36   59      20      3       4       1
37   62      15      5       5       1
38   33      25      8       2       0
39   37      10      5       3       0
40   50      20      2       4       1
41   47      12      8       0       0
42   69      20      5       4       1
43   63      20      4       5       1
44   39      15      7       2       0
45   21      20      8       3       0
46   31      20      9       4       0
47   28      10      4       1       0
48   53      20      6       3       1
49   62      20      5       6       1
50   42      12      6       2       0
51   44      30      1       6       1
52   26      34      1       8       1
53   35      20      5       1       0
54   26      13      6       1       0
55   77      20      5       4       1
56   75      15      3       5       1
57   43      30      3       8       1
58   51      25      9       0       0

In [ ]:
# we need to take Features seperately as "X"
X = df.iloc[:,:4]   # OR df.iloc[:,:-1]
print(X)

    Age  Smokes  AreaQ  Alkhol
0    35       3      5       4
1    27      20      2       5
2    30       0      5       2
3    28       0      8       1
4    68       4      5       6
5    34       0     10       0
6    58      15     10       0
7    22      12      5       2
8    45       2      6       0
9    52      18      4       5
10   33       4      8       0
11   18      10      6       3
12   25       2      5       1
13   28      20      2       8
14   34      25      4       8
15   39      18      8       1
16   42      22      3       5
17   19      12      8       0
18   62       5      4       3
19   73      10      7       6
20   55      15      1       3
21   33       8      8       1
22   22      20      6       2
23   44       5      8       1
24   77       3      2       6
25   21      20      5       3
26   37      15      6       2
27   34      12      8       0
28   55      20      1       4
29   40      20      2       7
30   36      13      5       2
31   56      20      3       3
32   47      15      1       8
33   62      25      3       4
34   26      10      7       2
35   25      20      8       2
36   59      20      3       4
37   62      15      5       5
38   33      25      8       2
39   37      10      5       3
40   50      20      2       4
41   47      12      8       0
42   69      20      5       4
43   63      20      4       5
44   39      15      7       2
45   21      20      8       3
46   31      20      9       4
47   28      10      4       1
48   53      20      6       3
49   62      20      5       6
50   42      12      6       2
51   44      30      1       6
52   26      34      1       8
53   35      20      5       1
54   26      13      6       1
55   77      20      5       4
56   75      15      3       5
57   43      30      3       8
58   51      25      9       0

In [ ]:
# we need to take Target seperately as "y"
y = df.iloc[:,-1]
y

0     1
1     1
2     0
3     0
4     1
5     0
6     0
7     0
8     0
9     1
10    0
11    0
12    0
13    1
14    1
15    0
16    1
17    0
18    1
19    1
20    1
21    0
22    0
23    0
24    1
25    0
26    0
27    0
28    1
29    1
30    0
31    1
32    1
33    1
34    0
35    0
36    1
37    1
38    0
39    0
40    1
41    0
42    1
43    1
44    0
45    0
46    0
47    0
48    1
49    1
50    0
51    1
52    1
53    0
54    0
55    1
56    1
57    1
58    0
Name: Result, dtype: int64

In [ ]:
# Converting all the features-values to Normalised/Standardised value
# By using Scaling
from sklearn.preprocessing import MinMaxScaler
Scaler = MinMaxScaler()
Scaler.fit(X)
X_Scaled = Scaler.transform(X)
X_Scaled

array([[0.28813559, 0.08823529, 0.44444444, 0.5       ],
       [0.15254237, 0.58823529, 0.11111111, 0.625     ],
       [0.20338983, 0.        , 0.44444444, 0.25      ],
       [0.16949153, 0.        , 0.77777778, 0.125     ],
       [0.84745763, 0.11764706, 0.44444444, 0.75      ],
       [0.27118644, 0.        , 1.        , 0.        ],
       [0.6779661 , 0.44117647, 1.        , 0.        ],
       [0.06779661, 0.35294118, 0.44444444, 0.25      ],
       [0.45762712, 0.05882353, 0.55555556, 0.        ],
       [0.57627119, 0.52941176, 0.33333333, 0.625     ],
       [0.25423729, 0.11764706, 0.77777778, 0.        ],
       [0.        , 0.29411765, 0.55555556, 0.375     ],
       [0.11864407, 0.05882353, 0.44444444, 0.125     ],
       [0.16949153, 0.58823529, 0.11111111, 1.        ],
       [0.27118644, 0.73529412, 0.33333333, 1.        ],
       [0.3559322 , 0.52941176, 0.77777778, 0.125     ],
       [0.40677966, 0.64705882, 0.22222222, 0.625     ],
       [0.01694915, 0.35294118, 0.77777778, 0.        ],
       [0.74576271, 0.14705882, 0.33333333, 0.375     ],
       [0.93220339, 0.29411765, 0.66666667, 0.75      ],
       [0.62711864, 0.44117647, 0.        , 0.375     ],
       [0.25423729, 0.23529412, 0.77777778, 0.125     ],
       [0.06779661, 0.58823529, 0.55555556, 0.25      ],
       [0.44067797, 0.14705882, 0.77777778, 0.125     ],
       [1.        , 0.08823529, 0.11111111, 0.75      ],
       [0.05084746, 0.58823529, 0.44444444, 0.375     ],
       [0.3220339 , 0.44117647, 0.55555556, 0.25      ],
       [0.27118644, 0.35294118, 0.77777778, 0.        ],
       [0.62711864, 0.58823529, 0.        , 0.5       ],
       [0.37288136, 0.58823529, 0.11111111, 0.875     ],
       [0.30508475, 0.38235294, 0.44444444, 0.25      ],
       [0.6440678 , 0.58823529, 0.22222222, 0.375     ],
       [0.49152542, 0.44117647, 0.        , 1.        ],
       [0.74576271, 0.73529412, 0.22222222, 0.5       ],
       [0.13559322, 0.29411765, 0.66666667, 0.25      ],
       [0.11864407, 0.58823529, 0.77777778, 0.25      ],
       [0.69491525, 0.58823529, 0.22222222, 0.5       ],
       [0.74576271, 0.44117647, 0.44444444, 0.625     ],
       [0.25423729, 0.73529412, 0.77777778, 0.25      ],
       [0.3220339 , 0.29411765, 0.44444444, 0.375     ],
       [0.54237288, 0.58823529, 0.11111111, 0.5       ],
       [0.49152542, 0.35294118, 0.77777778, 0.        ],
       [0.86440678, 0.58823529, 0.44444444, 0.5       ],
       [0.76271186, 0.58823529, 0.33333333, 0.625     ],
       [0.3559322 , 0.44117647, 0.66666667, 0.25      ],
       [0.05084746, 0.58823529, 0.77777778, 0.375     ],
       [0.22033898, 0.58823529, 0.88888889, 0.5       ],
       [0.16949153, 0.29411765, 0.33333333, 0.125     ],
       [0.59322034, 0.58823529, 0.55555556, 0.375     ],
       [0.74576271, 0.58823529, 0.44444444, 0.75      ],
       [0.40677966, 0.35294118, 0.55555556, 0.25      ],
       [0.44067797, 0.88235294, 0.        , 0.75      ],
       [0.13559322, 1.        , 0.        , 1.        ],
       [0.28813559, 0.58823529, 0.44444444, 0.125     ],
       [0.13559322, 0.38235294, 0.55555556, 0.125     ],
       [1.        , 0.58823529, 0.44444444, 0.5       ],
       [0.96610169, 0.44117647, 0.22222222, 0.625     ],
       [0.42372881, 0.88235294, 0.22222222, 1.        ],
       [0.55932203, 0.73529412, 0.88888889, 0.        ]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_Scaled,y,test_size = 0.3,random_state = 11)

In [ ]:
X_train.shape,y_train.shape

((41, 4), (41,))

In [ ]:
X_test.shape,y_test.shape

((18, 4), (18,))

In [ ]:
# Model Building
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
# Prediction based on X_test
y_pred = knn.predict(X_test)
y_pred

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0])

In [ ]:
# y_test contains the actual values
y_test.values

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred)*100)

100.0

In [ ]:
y_new = knn.predict(Scaler.transform([[78,6,7,6]]))
if y_new.item()==1:
  print("Person will suffer lung cancer")
else:
  print("Person will not suffer lung cancer")
# here the out put will be with an error because the features is in the form dataframes to convert it into tthe form of array the error wil be solved for that when we add features to X use .values with it

Person will suffer lung cancer

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

To save a model(created during predictions) we use **pickle** in Machine Learning

In [ ]:
import pickle
pickle.dump(knn,open('model_knn.sav','wb'))

In [ ]:
pickle.dump(Scaler,open('scaler_sav','wb'))

In [ ]:
! pip list

Package                                  Version
---------------------------------------- --------------------
absl-py                                  1.4.0
accelerate                               1.12.0
access                                   1.1.9
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.2
aiosignal                                1.4.0
aiosqlite                                0.21.0
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.17.2
altair                                   5.5.0
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.11.0
anywidget                                0.9.21
argon2-cffi                              25.1.0
argon2-cffi-bindings                     25.1.0
array_record                             0.8.3
arrow                                    1.4.0
arviz                                    0.22.0
astropy                                  7.1.1
astropy-iers-data                        0.2025.11.24.0.39.11
astunparse                               1.6.3
atpublic                                 5.1
attrs                                    25.4.0
audioread                                3.1.0
Authlib                                  1.6.5
autograd                                 1.8.0
babel                                    2.17.0
backcall                                 0.2.0
beartype                                 0.22.6
beautifulsoup4                           4.13.5
betterproto                              2.0.0b6
bigframes                                2.29.1
bigquery-magics                          0.10.3
bleach                                   6.3.0
blinker                                  1.9.0
blis                                     1.3.3
blobfile                                 3.1.0
blosc2                                   3.11.1
bokeh                                    3.7.3
Bottleneck                               1.4.2
bqplot                                   0.12.45
branca                                   0.8.2
brotli                                   1.2.0
CacheControl                             0.14.4
cachetools                               6.2.2
catalogue                                2.0.10
certifi                                  2025.11.12
cffi                                     2.0.0
chardet                                  5.2.0
charset-normalizer                       3.4.4
chex                                     0.1.90
clarabel                                 0.11.1
click                                    8.3.1
click-plugins                            1.1.1.2
cligj                                    0.7.2
cloudpathlib                             0.23.0
cloudpickle                              3.1.2
cmake                                    3.31.10
cmdstanpy                                1.3.0
colorcet                                 3.1.0
colorlover                               0.3.0
colour                                   0.1.5
community                                1.0.0b1
confection                               0.1.5
cons                                     0.4.7
contourpy                                1.3.3
cramjam                                  2.11.0
cryptography                             43.0.3
cuda-bindings                            12.9.4
cuda-core                                0.3.2
cuda-pathfinder                          1.3.2
cuda-python                              12.9.4
cuda-toolkit                             12.9.1
cudf-cu12                                25.10.0
cudf-polars-cu12                         25.10.0
cufflinks                                0.17.3
cuml-cu12                                25.10.0
cupy-cuda12x                             13.6.0
curl_cffi                                0.13.0
cvxopt                                   1.3.2
cvxpy                                    1.6.7
cycler                                   0.12.1
cyipopt                                  1.5.0
cymem                                    2.0.13
Cython                                   3.0.12
dask                                     2025.9.1
dask-cuda                                25.10.0
dask-cudf-cu12                           25.10.0
dataproc-spark-connect                   0.8.3
datasets                                 4.0.0
db-dtypes                                1.4.4
dbus-python                              1.2.18
debugpy                                  1.8.15
decorator                                4.4.2
defusedxml                               0.7.1
deprecation                              2.1.0
diffusers                                0.35.2
dill                                     0.3.8
distributed                              2025.9.1
distributed-ucxx-cu12                    0.46.0
distro                                   1.9.0
dlib                                     19.24.6
dm-tree                                  0.1.9
docstring_parser                         0.17.0
docutils                                 0.21.2
dopamine_rl                              4.1.2
duckdb                                   1.3.2
earthengine-api                          1.5.24
easydict                                 1.13
editdistance                             0.8.1
eerepr                                   0.1.2
einops                                   0.8.1
en_core_web_sm                           3.8.0
entrypoints                              0.4
esda                                     2.8.0
et_xmlfile                               2.0.0
etils                                    1.13.0
etuples                                  0.3.10
Farama-Notifications                     0.0.4
fastai                                   2.8.5
fastapi                                  0.118.3
fastcore                                 1.8.16
fastdownload                             0.0.7
fastjsonschema                           2.21.2
fastprogress                             1.0.3
fastrlock                                0.8.3
fasttransform                            0.0.2
ffmpy                                    1.0.0
filelock                                 3.20.0
fiona                                    1.10.1
firebase-admin                           6.9.0
Flask                                    3.1.2
flatbuffers                              25.9.23
flax                                     0.10.7
folium                                   0.20.0
fonttools                                4.60.1
fqdn                                     1.5.1
frozendict                               2.4.7
frozenlist                               1.8.0
fsspec                                   2025.3.0
future                                   1.0.0
gast                                     0.6.0
gcsfs                                    2025.3.0
GDAL                                     3.8.4
gdown                                    5.2.0
geemap                                   0.35.3
geocoder                                 1.38.1
geographiclib                            2.1
geopandas                                1.1.1
geopy                                    2.4.1
giddy                                    2.3.6
gin-config                               0.5.0
gitdb                                    4.0.12
GitPython                                3.1.45
glob2                                    0.7
google                                   3.0.0
google-adk                               1.19.0
google-ai-generativelanguage             0.6.15
google-api-core                          2.28.1
google-api-python-client                 2.187.0
google-auth                              2.43.0
google-auth-httplib2                     0.2.1
google-auth-oauthlib                     1.2.2
google-cloud-aiplatform                  1.128.0
google-cloud-appengine-logging           1.7.0
google-cloud-audit-log                   0.4.0
google-cloud-bigquery                    3.38.0
google-cloud-bigquery-connection         1.19.0
google-cloud-bigquery-storage            2.34.0
google-cloud-bigtable                    2.34.0
google-cloud-core                        2.5.0
google-cloud-dataproc                    5.23.0
google-cloud-datastore                   2.21.0
google-cloud-discoveryengine             0.13.12
google-cloud-firestore                   2.21.0
google-cloud-functions                   1.21.0
google-cloud-language                    2.18.0
google-cloud-logging                     3.12.1
google-cloud-monitoring                  2.28.0
google-cloud-resource-manager            1.15.0
google-cloud-secret-manager              2.25.0
google-cloud-spanner                     3.59.0
google-cloud-speech                      2.34.0
google-cloud-storage                     3.6.0
google-cloud-trace                       1.17.0
google-cloud-translate                   3.23.0
google-colab                             1.0.0
google-crc32c                            1.7.1
google-genai                             1.52.0
google-generativeai                      0.8.5
google-pasta                             0.2.0
google-resumable-media                   2.8.0
googleapis-common-protos                 1.72.0
googledrivedownloader                    1.1.0
gradio                                   5.50.0
gradio_client                            1.14.0
graphviz                                 0.21
greenlet                                 3.2.4
groovy                                   0.1.2
grpc-google-iam-v1                       0.14.3
grpc-interceptor                         0.15.4
grpcio                                   1.76.0
grpcio-status                            1.71.2
grpclib                                  0.4.8
gspread                                  6.2.1
gspread-dataframe                        4.0.0
gym                                      0.25.2
gym-notices                              0.1.0
gymnasium                                1.2.2
h11                                      0.16.0
h2                                       4.3.0
h5netcdf                                 1.7.3
h5py                                     3.15.1
hdbscan                                  0.8.40
hf_transfer                              0.1.9
hf-xet                                   1.2.0
highspy                                  1.12.0
holidays                                 0.85
holoviews                                1.22.0
hpack                                    4.1.0
html5lib                                 1.1
httpcore                                 1.0.9
httpimport                               1.4.1
httplib2                                 0.31.0
httpx                                    0.28.1
httpx-sse                                0.4.3
huggingface-hub                          0.36.0
humanize                                 4.14.0
hyperframe                               6.1.0
hyperopt                                 0.2.7
ibis-framework                           9.5.0
idna                                     3.11
ImageIO                                  2.37.2
imageio-ffmpeg                           0.6.0
imagesize                                1.4.1
imbalanced-learn                         0.14.0
immutabledict                            4.2.2
importlib_metadata                       8.7.0
importlib_resources                      6.5.2
imutils                                  0.5.4
inequality                               1.1.2
inflect                                  7.5.0
iniconfig                                2.3.0
intel-cmplr-lib-ur                       2025.3.1
intel-openmp                             2025.3.1
ipyevents                                2.0.4
ipyfilechooser                           0.6.0
ipykernel                                6.17.1
ipyleaflet                               0.20.0
ipyparallel                              8.8.0
ipython                                  7.34.0
ipython-genutils                         0.2.0
ipython-sql                              0.5.0
ipytree                                  0.2.2
ipywidgets                               7.7.1
isoduration                              20.11.0
itsdangerous                             2.2.0
jaraco.classes                           3.4.0
jaraco.context                           6.0.1
jaraco.functools                         4.3.0
jax                                      0.7.2
jax-cuda12-pjrt                          0.7.2
jax-cuda12-plugin                        0.7.2
jaxlib                                   0.7.2
jeepney                                  0.9.0
jieba                                    0.42.1
Jinja2                                   3.1.6
jiter                                    0.12.0
joblib                                   1.5.2
jsonpatch                                1.33
jsonpickle                               4.1.1
jsonpointer                              3.0.0
jsonschema                               4.25.1
jsonschema-specifications                2025.9.1
jupyter_client                           7.4.9
jupyter-console                          6.6.3
jupyter_core                             5.9.1
jupyter-events                           0.12.0
jupyter_kernel_gateway                   2.5.2
jupyter-leaflet                          0.20.0
jupyter_server                           2.14.0
jupyter_server_terminals                 0.5.3
jupyterlab_pygments                      0.3.0
jupyterlab_widgets                       3.0.16
jupytext                                 1.18.1
kaggle                                   1.7.4.5
kagglehub                                0.3.13
keras                                    3.10.0
keras-hub                                0.21.1
keras-nlp                                0.21.1
keyring                                  25.7.0
keyrings.google-artifactregistry-auth    1.1.2
kiwisolver                               1.4.9
langchain                                1.1.0
langchain-core                           1.1.0
langgraph                                1.0.3
langgraph-checkpoint                     3.0.1
langgraph-prebuilt                       1.0.5
langgraph-sdk                            0.2.10
langsmith                                0.4.47
lark                                     1.3.1
launchpadlib                             1.10.16
lazr.restfulclient                       0.14.4
lazr.uri                                 1.0.6
lazy_loader                              0.4
libclang                                 18.1.1
libcudf-cu12                             25.10.0
libcugraph-cu12                          25.10.1
libcuml-cu12                             25.10.0
libkvikio-cu12                           25.10.0
libpysal                                 4.13.0
libraft-cu12                             25.10.0
librmm-cu12                              25.10.0
librosa                                  0.11.0
libucx-cu12                              1.19.0
libucxx-cu12                             0.46.0
lightgbm                                 4.6.0
linkify-it-py                            2.0.3
llvmlite                                 0.43.0
locket                                   1.0.0
logical-unification                      0.4.7
lxml                                     6.0.2
Mako                                     1.3.10
mapclassify                              2.10.0
Markdown                                 3.10
markdown-it-py                           4.0.0
MarkupSafe                               3.0.3
matplotlib                               3.10.0
matplotlib-inline                        0.2.1
matplotlib-venn                          1.1.2
mcp                                      1.22.0
mdit-py-plugins                          0.5.0
mdurl                                    0.1.2
mgwr                                     2.2.1
miniKanren                               1.0.5
missingno                                0.5.2
mistune                                  3.1.4
mizani                                   0.13.5
mkl                                      2025.3.0
ml_dtypes                                0.5.4
mlxtend                                  0.23.4
momepy                                   0.10.0
more-itertools                           10.8.0
moviepy                                  1.0.3
mpmath                                   1.3.0
msgpack                                  1.1.2
multidict                                6.7.0
multipledispatch                         1.0.0
multiprocess                             0.70.16
multitasking                             0.0.12
murmurhash                               1.0.15
music21                                  9.9.1
namex                                    0.1.0
narwhals                                 2.12.0
natsort                                  8.4.0
nbclassic                                1.3.3
nbclient                                 0.10.2
nbconvert                                7.16.6
nbformat                                 5.10.4
ndindex                                  1.10.1
nest-asyncio                             1.6.0
networkx                                 3.6
nibabel                                  5.3.2
nltk                                     3.9.1
notebook                                 6.5.7
notebook_shim                            0.2.4
numba                                    0.60.0
numba-cuda                               0.19.1
numexpr                                  2.14.1
numpy                                    2.0.2
nvidia-cublas-cu12                       12.6.4.1
nvidia-cuda-cccl-cu12                    12.9.27
nvidia-cuda-cupti-cu12                   12.6.80
nvidia-cuda-nvcc-cu12                    12.5.82
nvidia-cuda-nvrtc-cu12                   12.6.77
nvidia-cuda-runtime-cu12                 12.6.77
nvidia-cudnn-cu12                        9.10.2.21
nvidia-cufft-cu12                        11.3.0.4
nvidia-cufile-cu12                       1.11.1.6
nvidia-curand-cu12                       10.3.7.77
nvidia-cusolver-cu12                     11.7.1.2
nvidia-cusparse-cu12                     12.5.4.2
nvidia-cusparselt-cu12                   0.7.1
nvidia-ml-py                             13.580.82
nvidia-nccl-cu12                         2.27.5
nvidia-nvjitlink-cu12                    12.6.85
nvidia-nvshmem-cu12                      3.3.20
nvidia-nvtx-cu12                         12.6.77
nvtx                                     0.2.13
nx-cugraph-cu12                          25.10.0
oauth2client                             4.1.3
oauthlib                                 3.3.1
omegaconf                                2.3.0
onemkl-license                           2025.3.0
openai                                   2.8.1
opencv-contrib-python                    4.12.0.88
opencv-python                            4.12.0.88
opencv-python-headless                   4.12.0.88
openpyxl                                 3.1.5
opentelemetry-api                        1.37.0
opentelemetry-exporter-gcp-logging       1.11.0a0
opentelemetry-exporter-gcp-monitoring    1.11.0a0
opentelemetry-exporter-gcp-trace         1.11.0
opentelemetry-exporter-otlp-proto-common 1.37.0
opentelemetry-exporter-otlp-proto-http   1.37.0
opentelemetry-proto                      1.37.0
opentelemetry-resourcedetector-gcp       1.11.0a0
opentelemetry-sdk                        1.37.0
opentelemetry-semantic-conventions       0.58b0
opt_einsum                               3.4.0